# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_options',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'Pagseguro'), ('paypal', 'Paypal')], default='deposit', max_length=20, verbose_name='Opção de Pagamento'),
        ),
    ]
